name: click_a_clean
description: Click A Clean

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  camera: ^0.5.8+2
  image_picker: ^0.6.1+4

  path_provider: ^1.1.0
  path: ^1.6.2
  esys_flutter_share: ^1.0.2
  percent_indicator: ^2.1.5
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.7+3
  flutter_launcher_icons: ^0.7.3
  http: ^0.12.1
  email_validator: ^1.0.0
  table_calendar: ^2.2.3
  # Google Maps plugin
  google_maps_flutter: ^0.5.21+8
    # Geolocator plugin
  geolocator: ^5.1.4+2
  geocoder: ^0.2.1
  location: ^3.0.0
  flutter_polyline_points: ^0.1.0
  progress_dialog: ^1.2.4
  mime: ^0.9.6+3
  video_player: ^0.10.11+2

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  firebase_dynamic_links: ^0.5.3
  progress_hud: ^1.1.0
  connectivity: ^2.0.2
  url_launcher: ^5.7.6
  webview_flutter: ^1.0.0
  http_auth: ^0.3.1
  firebase_messaging: ^6.0.0
  cloud_firestore: ^0.12.5
  stripe_payment: ^1.0.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
flutter_icons:

  android: true
  ios: true
  image_path: "assets/images/logo_img.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets :

    - assets/images/map.jpg
    - assets/images/logo_img.png
    - assets/images/home_option.png
    - assets/images/walk-2x.png
    - assets/images/walk3-2x.png
    - assets/images/walk2-2x.png
    - assets/images/welcome@2x.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/logo-white.png
    - assets/images/next_icon.png
    - assets/images/india_flag.png
    - assets/images/orconnectwith@2x.png
    - assets/images/success.png
    - assets/images/delete.png
    - assets/images/next_icon.png
    - assets/images/car.png
    - assets/images/van.png
    - assets/images/car_blue.png
    - assets/images/car_three.png
    - assets/images/location_icon_white.png
    - assets/images/selected_icon.png
    - assets/images/office_domestic.png
    - assets/images/B&Bdomestic.png
    - assets/images/home_domestic.png
    - assets/images/flat_domestic.png
    - assets/images/house_domestic.png
    - assets/images/dog-bg.png
    - assets/images/car-bg.png
    - assets/images/map-new.png
    - assets/images/white-logo.svg
    - assets/images/main-logo.svg
    - assets/images/p_user_icon.svg
    - assets/images/seek-bar-2.svg
    - assets/images/p_seek-bar.svg
    - assets/images/next-icon-orange.svg
    - assets/images/seek-bar-2.svg
    - assets/images/driving.svg
    - assets/images/national-id.svg
    - assets/images/passport.svg
    - assets/images/allow-camera-access.svg
    - assets/images/tap-allow-icon.svg
    - assets/images/check.png
    - assets/flags/ad.png
    - assets/images/add_photos.png
    - assets/images/background_image.png
    - assets/images/noti.png
    - assets/images/delete_icon.png
    - assets/images/cancel_btn.png
    - assets/images/circle-unfilled.png
    - assets/images/circle-filled.png
    - assets/images/avatar_bg.png
    - assets/images/icon_logo.png




    # To add assets to your application, add an assets section, like this:
    #   assets:
    #    -images/logo.png
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add assets to your application, add an assets section, like this:
  #   assets:
  #    -images/logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
